cargo-features = ["edition2024"]
[package]
name = "Victors_website"
version = "0.1.0"
edition = "2024"


[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.11", features = ["csr", "nightly"] }
